---
deployment:
  tasks:
    - export DEPLOYPATH=/home2/centena2/public_html/
    - /bin/cp -R components $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    - /bin/cp -R pages $DEPLOYPATH
    - /bin/cp -R public $DEPLOYPATH
    - /bin/cp -R scss $DEPLOYPATH
    - /bin/cp index.html $DEPLOYPATH